; generated by coffee-basic/0.0.2

if (A_IsAdmin != true) {
  Run *RunAs "%A_ScriptFullPath%"
  ExitApp
}

#KeyHistory 0
#MaxThreads 20
#NoEnv
#Persistent
#SingleInstance Force
#UseHook

CoordMode Mouse, Client
CoordMode Pixel, Client
CoordMode ToolTip, Client
SendMode Event
SetBatchLines 100ms
SetKeyDelay 0, 50
SetMouseDelay 0, 50

; global variable

global $cd := {}
global $ts := {}
global $isChanting := false
global $hp := 0
global $isMoving := false
global $mp := 0
global $isTargeting := false
global $step := 0
global $level := 80
global $skill := {}
global $watcher := {}
global $isIM := false
global $isReporting := true

; function

toggleView() {
  GetKeyState __value__, 2joy5
  isPressing := __value__ == "D"
  if !(isPressing) {
    SetTimer toggleView, Off
    Send {ctrl up}{up up}
    return
  }
  GetKeyState state, 2joyr
  if (state < 20) {
    Send {ctrl down}{up down}
  }
}

attack() {
  trigger := getCurrentTrigger()
  if !(trigger) {
    return
  }
  use("获取状态")
  use("报告")
  if !(use("索敌")) {
    return
  }
  if (trigger == "right") {
    attackS()
    return
  }
  if (trigger == "both") {
    attackM()
    return
  }
}

bindAttack() {
  GetKeyState __value__, 2joy4
  isPressing := __value__ == "D"
  if !(isPressing) {
    SetTimer bindAttack, Off
    return
  }
  attack()
}

calcCd(name) {
  result := $cd[name] - (A_TickCount - $ts[name])
  if !(result > 0) {
    return 0
  }
  result := Round(result / 1000)
  return result
}

checkChanting() {
  if ($isMoving) {
    $isChanting := false
    return
  }
  PixelGetColor color, 1130, 865, RGB
  $isChanting := color == 0x2B1B13
}

checkHp() {
  PixelSearch x, y, 21, 36, 168, 36, 0x58483E, 10, Fast RGB
  if !(x) {
    $hp := 100
    return
  }
  percent := (x - 21) * 100 / (168 - 21)
  percent := Round(percent)
  $hp := percent
}

checkMoving() {
  GetKeyState dis, 2joyx
  if (dis < 40 or dis > 60) {
    $isMoving := true
    return
  }
  GetKeyState dis, 2joyy
  if (dis < 40 or dis > 60) {
    $isMoving := true
    return
  }
  $isMoving := false
}

checkMp() {
  PixelSearch x, y, 181, 36, 328, 36, 0x58483E, 10, Fast RGB
  if !(x) {
    $mp := 100
    return
  }
  percent := (x - 181) * 100 / (328 - 181)
  percent := Round(percent)
  $mp := percent
}

checkTargeting() {
  PixelGetColor color, 650, 65, RGB
  if (color == 0xFF8888) {
    $isTargeting := true
    return
  }
  if (color == 0xFFC888) {
    $isTargeting := true
    return
  }
  if (color == 0xEBD788) {
    $isTargeting := true
    return
  }
  if (color == 0xFFB1FF) {
    $isTargeting := true
    return
  }
  $isTargeting := false
}

clearTip() {
  ToolTip
}

clearWatcher(name, type := "hasUsed") {
  if (type == "hasUsed") {
    if !(hasUsed(name)) {
      return
    }
  }
  else if (type == "status") {
    if !(hasStatus(name)) {
      return
    }
  }
  if !($watcher[name]) {
    MsgBox % "invalid watcher: " . name . ""
    return
  }
  __timer__ := $watcher[name]
  SetTimer %__timer__%, Off
  $ts[name] := A_TickCount - $cd.技能施放补正
  return true
}

getCurrentTrigger() {
  GetKeyState __value__, 2joy7
  isLT := __value__ == "D"
  GetKeyState __value__, 2joy8
  isRT := __value__ == "D"
  if (isLT and isRT) {
    return "both"
  }
  if (isLT) {
    return "left"
  }
  if (isRT) {
    return "right"
  }
  return
}

hasStatus(name) {
  ImageSearch x, y, 725, 840, 925, 875, % A_ScriptDir . "\" . "image\" . name . ".png"
  return x > 0 and y > 0
}

hasStatusByTarget(name) {
  ImageSearch x, y, 725, 765, 925, 800, % A_ScriptDir . "\" . "image\" . name . ".png"
  return x > 0 and y > 0
}

hasUsed(name) {
  ImageSearch x, y, 60, 915, 225, 975, % A_ScriptDir . "\" . "image\" . name . ".png"
  return x > 0 and y > 0
}

makeReportMsg(msg, list) {
  for __i__, name in list {
    result := calcCd(name)
    if !(result > 1) {
      continue
    }
    msg := "" . msg . "`n" . name . "：" . result . "s"
  }
  return msg
}

resetKey() {
  Send {alt up}
  Send {ctrl up}
  Send {shift up}
  MouseMove 410, 640, 0
}

resetStep() {
  $step := 0
}

resetTs() {
  for key, value in $ts {
    $ts[key] := 0
  }
}

setLevel() {
  InputBox $level, , % "input level", , , , , , , , % $level
  if !($level > 0) {
    $level := 80
  }
  if ($level < 10) {
    $level := $level * 10
  }
  resetTs()
}

use(name, option := false) {
  if !($skill[name]) {
    MsgBox % "invalid skill: " . name . ""
    return
  }
  return $skill[name].Call(option)
}

watch(name) {
  if !($watcher[name]) {
    MsgBox % "invalid watcher: " . name . ""
    return
  }
  return $watcher[name]()
}

checkIM() {
  $isIM := hasStatus("光速")
}

__$skill_dot_中断咏唱__() {
  if !($isChanting) {
    return
  }
  Send {space}
}

__$skill_dot_冲刺__() {
  Send {shift down}{-}{shift up}
}

__$skill_dot_空白信息__() {
  Send {shift down}{=}{shift up}
}

__$skill_dot_索敌__() {
  checkTargeting()
  if ($isTargeting) {
    return true
  }
  Send {f11}
  checkTargeting()
  return $isTargeting
}

__$skill_dot_先天禀赋__() {
  if !($level >= 15) {
    return
  }
  if ($isIM) {
    return
  }
  if !(A_TickCount - $ts.先天禀赋 > $cd.先天禀赋) {
    return
  }
  Send {alt down}{7}{alt up}
  $ts.先天禀赋 := A_TickCount - $cd.先天禀赋 + $cd.技能施放补正
  SetTimer __$watcher_dot_先天禀赋__, % $cd.技能施放判断间隔
  return true
}

__$watcher_dot_先天禀赋__() {
  clearWatcher("先天禀赋")
}

__$skill_dot_光速__() {
  if !(A_TickCount - $ts.光速 > $cd.光速) {
    return
  }
  Send {alt down}{4}{alt up}
  $ts.光速 := A_TickCount - $cd.光速 + $cd.技能施放补正
  SetTimer __$watcher_dot_光速__, % $cd.技能施放判断间隔
  return true
}

__$watcher_dot_光速__() {
  clearWatcher("光速", "status")
}

__$skill_dot_凶星__() {
  Send {alt down}{1}{alt up}
}

__$skill_dot_即刻咏唱__() {
  if !(A_TickCount - $ts.即刻咏唱 > $cd.即刻咏唱) {
    return
  }
  Send {shift down}{5}{shift up}
  $ts.即刻咏唱 := A_TickCount - $cd.即刻咏唱 + $cd.技能施放补正
  SetTimer __$watcher_dot_即刻咏唱__, % $cd.技能施放判断间隔
  return true
}

__$watcher_dot_即刻咏唱__() {
  clearWatcher("即刻咏唱", "status")
}

__$skill_dot_吉星__() {
  Send {alt down}{2}{alt up}
  return true
}

__$skill_dot_吉星相位__() {
  if !($level >= 34) {
    return
  }
  if ($isIM) {
    return
  }
  if !(A_TickCount - $ts.吉星相位 > $cd.吉星相位) {
    return
  }
  if (hasStatusByTarget("吉星相位")) {
    return
  }
  Send {alt down}{=}{alt up}
  $ts.吉星相位 := A_TickCount - $cd.吉星相位 + $cd.技能施放补正
  return true
}

__$skill_dot_康复__() {
  Send {shift down}{4}{shift up}
}

__$skill_dot_报告__() {
  if !($isReporting) {
    return
  }
  msg := "等级：" . $level . " / 魔力：" . $mp . "%"
  msg := "" . msg . "`n咏唱：" . $isChanting . " / 移动：" . $isMoving . ""
  msg := "" . msg . "`n耗时：" . A_TickCount - $ts.报告 . "ms`n"
  $ts.报告 := A_TickCount
  msg := makeReportMsg(msg, ["光速", "先天禀赋", "抽卡", "即刻咏唱", "醒梦"])
  ToolTip % msg, 410, 640
  SetTimer clearTip, Off
  SetTimer clearTip, % 0 - 10000
}

__$skill_dot_抽卡__() {
  if !($level >= 30) {
    return
  }
  if !(A_TickCount - $ts.抽卡 > $cd.抽卡) {
    return
  }
  Send {alt down}{9}{alt up}
  $ts.抽卡 := A_TickCount - $cd.抽卡 + $cd.技能施放补正
  SetTimer __$watcher_dot_抽卡__, % $cd.技能施放判断间隔
  return true
}

__$watcher_dot_抽卡__() {
  clearWatcher("抽卡")
}

__$skill_dot_出卡__() {
  if !($level >= 30) {
    return
  }
  Send {alt down}{-}{alt up}
  return true
}

__$skill_dot_烧灼__(isForced := false) {
  if ($isIM) {
    return
  }
  if !(isForced) {
    if (hasStatusByTarget("烧灼")) {
      return
    }
  }
  Send {alt down}{3}{alt up}
  return true
}

__$skill_dot_生辰__() {
  if !($level >= 12) {
    return
  }
  Send {alt down}{5}{alt up}
  return true
}

__$skill_dot_福星__() {
  if !($level >= 26) {
    return
  }
  Send {alt down}{8}{alt up}
  return true
}

__$skill_dot_获取状态__() {
  if (A_TickCount - $ts.获取状态 > 10000) {
    use("空白信息")
    use("空白信息")
    use("空白信息")
  }
  $ts.获取状态 := A_TickCount
  checkMoving()
  checkChanting()
  checkIM()
}

__$skill_dot_醒梦__() {
  if !(A_TickCount - $ts.醒梦 > $cd.醒梦) {
    return
  }
  checkMp()
  if ($mp > 50) {
    return
  }
  Send {shift down}{6}{shift up}
  $ts.醒梦 := A_TickCount - $cd.醒梦 + $cd.技能施放补正
  SetTimer __$watcher_dot_醒梦__, % $cd.技能施放判断间隔
  return true
}

__$watcher_dot_醒梦__() {
  clearWatcher("醒梦", "status")
}

__$skill_dot_重力__() {
  if !($level >= 45) {
    return
  }
  Send {ctrl down}{3}{ctrl up}
  return true
}

__$skill_dot_阳星__() {
  Send {alt down}{5}{alt up}
  return true
}

__$skill_dot_阳星相位__() {
  if !($level >= 42) {
    return
  }
  if !(A_TickCount - $ts.阳星相位 > $cd.阳星相位) {
    return
  }
  Send {ctrl down}{2}{ctrl up}
  SetTimer __$watcher_dot_阳星相位__, % $cd.技能施放判断间隔
  return true
}

__$watcher_dot_阳星相位__() {
  clearWatcher("阳星相位")
}

attackS() {
  if ($isChanting) {
    return
  }
  use("醒梦")
  use("光速")
  use("抽卡")
  if ($isIM) {
    use("凶星")
    return
  }
  if ($isMoving) {
    use("烧灼", true)
    return
  }
  if (use("烧灼")) {
    return
  }
  use("凶星")
}

attackM() {
  if ($isChanting) {
    return
  }
  use("醒梦")
  use("光速")
  use("抽卡")
  if ($isIM) {
    use("重力")
    return
  }
  if ($isMoving) {
    use("烧灼", true)
    return
  }
  use("重力")
}

healS() {
  if ($isChanting) {
    return
  }
  if (use("先天禀赋")) {
    return
  }
  use("醒梦")
  use("光速")
  use("抽卡")
  if (use("吉星相位")) {
    return
  }
  if (use("福星")) {
    return
  }
  use("吉星")
}

healM() {
  if ($isChanting) {
    return
  }
  use("醒梦")
  use("光速")
  use("抽卡")
  if (use("阳星相位")) {
    return
  }
  use("阳星")
}

__$default__() {
  $cd.技能施放判断间隔 := 100
  $cd.技能施放补正 := 1500
  $skill.中断咏唱 := Func("__$skill_dot_中断咏唱__")
  $skill.冲刺 := Func("__$skill_dot_冲刺__")
  $skill.空白信息 := Func("__$skill_dot_空白信息__")
  $skill.索敌 := Func("__$skill_dot_索敌__")
  $ts.先天禀赋 := 0
  $cd.先天禀赋 := 40000
  $skill.先天禀赋 := Func("__$skill_dot_先天禀赋__")
  $watcher.先天禀赋 := Func("__$watcher_dot_先天禀赋__")
  $ts.光速 := 0
  $cd.光速 := 120000
  $skill.光速 := Func("__$skill_dot_光速__")
  $watcher.光速 := Func("__$watcher_dot_光速__")
  $skill.凶星 := Func("__$skill_dot_凶星__")
  $ts.即刻咏唱 := 0
  $cd.即刻咏唱 := 60000
  $skill.即刻咏唱 := Func("__$skill_dot_即刻咏唱__")
  $watcher.即刻咏唱 := Func("__$watcher_dot_即刻咏唱__")
  $skill.吉星 := Func("__$skill_dot_吉星__")
  $ts.吉星相位 := 0
  $cd.吉星相位 := 2500
  $skill.吉星相位 := Func("__$skill_dot_吉星相位__")
  $skill.康复 := Func("__$skill_dot_康复__")
  $ts.报告 := 0
  $skill.报告 := Func("__$skill_dot_报告__")
  $ts.抽卡 := 0
  $cd.抽卡 := 30000
  $skill.抽卡 := Func("__$skill_dot_抽卡__")
  $watcher.抽卡 := Func("__$watcher_dot_抽卡__")
  $skill.出卡 := Func("__$skill_dot_出卡__")
  $skill.烧灼 := Func("__$skill_dot_烧灼__")
  $skill.生辰 := Func("__$skill_dot_生辰__")
  $skill.福星 := Func("__$skill_dot_福星__")
  $ts.获取状态 := 0
  $skill.获取状态 := Func("__$skill_dot_获取状态__")
  $ts.醒梦 := 0
  $cd.醒梦 := 60000
  $skill.醒梦 := Func("__$skill_dot_醒梦__")
  $watcher.醒梦 := Func("__$watcher_dot_醒梦__")
  $skill.重力 := Func("__$skill_dot_重力__")
  $skill.阳星 := Func("__$skill_dot_阳星__")
  $ts.阳星相位 := 0
  $cd.阳星相位 := 15000
  $skill.阳星相位 := Func("__$skill_dot_阳星相位__")
  $watcher.阳星相位 := Func("__$watcher_dot_阳星相位__")
}

; default
__$default__()

; event

f5::
  resetKey()
  resetTs()
  SoundBeep
  setLevel()
return

^f5::
  resetKey()
  SoundBeep
  Reload
return

!f4::
  resetKey()
  SoundBeep
  ExitApp
return

2joy5::
  if !(getCurrentTrigger() == "both") {
    SetTimer toggleView, Off
    SetTimer toggleView, % 300
    return
  }
  Send {shift down}{tab}{shift up}
return

2joy6::
  if !(getCurrentTrigger() == "both") {
    return
  }
  Send {tab}
return

2joy12::
  if !(getCurrentTrigger()) {
    return
  }
  use("冲刺")
return

2joy4::
  if !(getCurrentTrigger()) {
    return
  }
  SetTimer bindAttack, Off
  SetTimer bindAttack, % 300
  attack()
return

2joy2::
  trigger := getCurrentTrigger()
  if !(trigger) {
    return
  }
  use("获取状态")
  use("报告")
  if (trigger == "right") {
    healS()
    return
  }
  if (trigger == "both") {
    healM()
    return
  }
return

2joy1::
  trigger := getCurrentTrigger()
  if !(trigger) {
    return
  }
  use("获取状态")
  use("报告")
  if (trigger == "right") {
    use("出卡")
    return
  }
  if (trigger == "both") {
    use("康复")
    return
  }
  if (trigger == "left") {
    use("即刻咏唱")
    use("生辰")
    return
  }
return

; eof