; generated by coffee-basic/0.0.2

#KeyHistory 0
#MaxThreads 20
#NoEnv
#Persistent
#SingleInstance Force
#UseHook

CoordMode Mouse, Client
CoordMode Pixel, Client
CoordMode ToolTip, Client
SendMode Event
SetBatchLines 100ms
SetKeyDelay 0, 50
SetMouseDelay 0, 50

; global variable

global a := "" . 1 . ""
global a := "" . true . ""
global a := "" . c . ""
global a := "" . x . ", " . y . ""
global a := "" . a . b . c . ""
global a := ""

; eof