; generated by coffee-basic/0.0.3

#KeyHistory 0
#MaxThreads 20
#NoEnv
#Persistent
#SingleInstance Force
#UseHook

CoordMode Mouse, Client
CoordMode Pixel, Client
CoordMode ToolTip, Client
SendMode Event
SetBatchLines 100ms
SetKeyDelay 0, 50
SetMouseDelay 0, 50

; global variable

global $ := {}
global tsClickLeft := 0

; function

fnTest() {
  $.beep()
}

checkLeft() {
  if ($.now() - tsClickLeft > 1000) {
    $.press("space")
  }
}

__$_dot_reload__() {
  Reload
}

__$_dot_exit__() {
  ExitApp
}

__$_dot_move__(x := 0, y := 0, speed := 0) {
  MouseMove x, y, speed
  return [x, y, speed]
}

__$_dot_click__(input) {
  if (!input) {
    Click
    return
  }
  Click % StrReplace input, ":", " "
}

__$_dot_now__() {
  return A_TickCount
}

__$_dot_beep__() {
  SoundBeep
}

__$default__() {
  $.reload := Func("__$_dot_reload__")
  $.exit := Func("__$_dot_exit__")
  $.move := Func("__$_dot_move__")
  $.click := Func("__$_dot_click__")
  $.now := Func("__$_dot_now__")
  $.beep := Func("__$_dot_beep__")
}

; event

f11::
  $.reload()
return

f12::
  $.exit()
return

f1::
  $.move(100, 100)
  $.click()
return

lbutton::
  tsClickLeft := $.now()
  setInterval("checkLeft", 300)
return

lbutton up::
  clearInterval("checkLeft")
  if ($.now() - tsClickLeft > 1000) {
    $.press("space:up")
  }
return

; eof