// interface
import { IData } from '../type'

// export
export default (data: IData) => {

  let result = [
    '; generated by coffee-basic/0.0.2'
  ]

  // mode admin
  if (data.mode.includes('admin'))
    result = [
      ...result,
      '',
      'if (A_IsAdmin != true) {',
      '  Run *RunAs "%A_ScriptFullPath%"',
      '  ExitApp',
      '}'
    ]

  result = [
    ...result,
    '',
    '#KeyHistory 0',
    '#MaxThreads 20',
    '#NoEnv',
    '#Persistent',
    '#SingleInstance Force',
    '#UseHook',
    '',
    'CoordMode Mouse, Client',
    'CoordMode Pixel, Client',
    'CoordMode ToolTip, Client',
    'SendMode Event',
    'SetBatchLines 100ms',
    'SetKeyDelay 0, 50',
    'SetMouseDelay 0, 50'
  ]

  //

  data.head = result
}